//reduce boilerplate when importing components by allowing them to grouped
export * from '@/components/ui/button'
export * from '@/components/ui/card'
export * from '@/components/ui/checkbox'
export * from '@/components/ui/dropdown-menu'
export * from '@/components/ui/form'
export * from '@/components/ui/input'
export * from '@/components/ui/label'
export * from '@/components/ui/select'
export * from '@/components/ui/switch'
export * from '@/components/ui/alert-dialog'
export * from '@/components/ui/popover'
export * from '@/components/ui/badge'
export * from '@/components/ui/checkbox'
export * from '@/components/ui/table'
export * from '@/components/ui/scroll-area'
export * from '@/components/ui/separator'
export * from '@/components/ui/command'
